#!/bin/bash
#
# DESCRIPTION
#	Invoke release build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR=<path>
#		export BUILD_NUMBER=<#>
#		source setEnv
#		./buildRelease
#
# HUDSON BUILD:
#	cd $WORKSPACE
#	export NLEXTERNALDIR=c:/hudson/jobs/source_main_external/workspace
#	source setEnv
#	./buildRelease
#
# DEBUG:
#	To debug ANT problems, add -v option to an ANT command. For example:
#		$ANT -v -f scripts/build_xlib.xml

export ANT_HOME=$NLEXTERNALDIR/apache-ant/apache-ant-1.10.12

source ../version_control

ANT=$ANT_HOME/bin/ant
LOG_FILE=buildRelease.log
BUILD_MANIFEST_FILE=build.manifest

(
set -x
# Extract Workspace and Hudson info (only if running on Hudson)
if [ -f ${WORKSPACE}/../config.xml ]; then
	${WORKSPACE}/scripts/getGitWorkspaceInfo.pl ${WORKSPACE}/../config.xml
fi

# Prepare environment
./configure --type=release || exit $?
source build.config

# Prepare dependencies
$ANT -f scripts/build_xlib.xml || exit $?

# Compile code and build installers
$ANT -f scripts/build_compile.xml || exit $?

# Compile code and build installers
$ANT -f scripts/build_analysis.xml || exit $?

# Publish installers and artifacts
$ANT -f scripts/build_publish.xml || exit $?

# Create and publish build manifest
scripts/createBuildManifest.pl $LOG_FILE > $BUILD_MANIFEST_FILE || exit $?
$ANT -f scripts/build_publish.xml manifest || exit $?
set +x
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}
