#pragma once
// TODO: Support localization?
// This is central place to define the text string shown in UI
#define OTKX_MESSAGEDLG_LABEL "NextLabs RMX"

#define IDS_ERR_DENY_OP "Operation Denied.\nYou do not have '%s' permission to perform this action on current model."
#define IDS_ERR_DENY_EDIT_CURRENT_MODEL "Operation Denied.\nYou do not have 'Edit' permission on current model but it is modified in session."
#define IDS_ERR_DENY_EDIT_DEP "Operation Denied.\nYou do not have 'Edit' permission on the following dependent file(s) but they are modified in session:"
#define IDS_ERR_DENY_OP_DEP "Operation Denied.\nYou do not have '%s' permission to perform this action on the following dependent file(s):"
#define IDS_ERR_DENY_EX_JTCURRENT_FMT "Operation Denied.\nYou do not have '%s' permission to export this model. Export button disabled."
#define IDS_ERR_DENY_EX_DEP_FMT "Operation Denied.\nYou do not have '%s' permission to export the following dependent file(s)."
#define IDS_ERR_DENY_EX_JTCURRENT_SURFFIX " Export button disabled."
#define IDS_ERR_DENY_OPEN "Operation Denied. \nYou do not have 'View' permission to open this protected file %s."
#define IDS_ERR_DENY_DISCARD_CHANGE "You do not have 'Edit' permission on the following files. The changes on them will be discarded.\nPlease reload them to avoid out-dated objects in session."
#define IDS_ERR_DENY_DELETE_EXPORTFILE "Operation Denied.\nYou do not have permission to export the following file(s). The exported file(s) is deleted."
#define IDS_ERR_DENY_EMAILATTACH "Operation Denied.\nYou are not allowed to directly send the object if it is protected or any dependent object is protected.\nPlease Save a Copy of object with RMX and attach to email."
#define IDS_ERR_DENY_IPEM_OP L"Operation Denied. You do not have permission to perform this action on the following file(s). Please deselect them and try again."
#define IDS_ERR_DENY_IPEM_OP_EDIT_REQUIRED L"\n'Edit' right required:"
#define IDS_ERR_DENY_IPEM_OP_SAVEASJT_REQUIRED L"\n'Save As' right required to export JT:"
#define IDS_ERR_DENY_IPEM_OP_SAVEJT L"Operation Denied. You do not have 'Save As' permission to export JT for the following file(s). Please deselect them and try again."
#define IDS_ERR_DENY_IPEM_OP_SAVEAS_REQUIRED L"\n'Save As' right required:"
#define IDS_ERR_DENY_IPEM_OP_SAVEAS_NOEDIT L"Operation Denied. You do not have 'Edit' permission to change the following file(s) but model(s) modified in session. Please deselect them and try again."
#define IDS_ERR_DENY_IPEM_OP_FMT L"Operation Denied. You do not have '%s' permission to perform this action on the following file(s). Please deselect them and try again."
#define IDS_ERR_DENY_IPEM_OP_LOSEFILE L"Operation Denied. The following protected files no longer exist in disk. Please deselect them and try again."
#define IDS_ERR_DENY_IPEM_OP_LOSTFILE_REQUIRED L"\nProtected file not exists in disk:"
#define IDS_ERR_DENY_OP_LOSEFILE "Operation Denied. The protected file for this model no longer exists in disk."
#define IDS_ERR_DENY_OP_DEP_LOSEFILE  "Operation Denied. The following protected files no longer exist in disk."
#define IDS_ERR_DENY_MAILATTACH  "Operation Denied.\nYou do not have 'Save As' permission to send an email with the following protected file(s) as zipped attachment."
#define IDS_ERR_DENY_NO_CURRMODEL "Operation Denied. No current model."
#define IDS_ERR_DENY_EDIT_MAILATTACH "Operation Denied.\nYou do not have 'Edit' permission to change the following file(s) but model(s) modified in session. \nDo not allow to send them."
#define IDS_ERR_DENY_DRWPREVIEW "Operation Denied.\nCannot preview due to the current model or its dependect file(s) protected."
#define IDS_ABOUT_TEXT "NexLabs Rights Management eXtension for Creo\nVersion %s (Build %s)\n\n@%s NextLabs Inc. All rights reserved."
#define IDS_WARN_SETRPMDIR_AFTER_PROTECT "Protect successfully, but fail to set file folder as SkyDRM secure folder.\nPlease manually set SkyDRM secure folder before reopenning the protected file"
#define IDS_WARN_REOPEN_AFTER_PROTECT "Protect successfully. Please reopen to access newly protected file"
#define IDS_WARN_SAVE_CHANGES "Below model(s) modified in session. Do you want to save changes and continue?\n%s"
#define IDS_WARN_SAVE_NEW_MODELS "Below new model(s) not saved yet. Do you want to save to disk and continue?\n%s"
#define IDS_WARN_SAVE_CURRENT_CHANGES "Current model modified in session. Do you want to save changes and continue?"
#define IDS_WARN_SAVE_CURRENT_MODEL "Current new model not saved yet. Do you want to save to disk and continue?"
#define IDS_ERROR_INCOMPLETE_OP "The active model has pending operations. Please complete these operations before protecting"
#define IDS_ERROR_CANNOT_ERASE_AFTER_PROTECT "Cannot erase the model. Being used in current session.\nPlease manually reopen the model dependent upon it and continue."
#define IDS_ERROR_DIRTY_TO_RELOAD "Cannot open. Model needs to reopen for the protection to take effect.\nPlease manually reopen the model dependent upon it and continue."