
set MSBUILD="C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe"
set BUILDTYPE=Release
set VERSION_MAJOR=3
set VERSION_MINOR=0
set VERSION_PATCH=0
SET version_BUILD=888
set MSBUILD_FLAGS=/t:rebuild /p:Configuration=%BUILDTYPE% /fl /p:VER_MAJOR=%VERSION_MAJOR% /p:VER_MINOR=%VERSION_MINOR% /p:VER_PATCH=%VERSION_PATCH% /p:VER_BUILD=%VERSION_BUILD%

set BUILD_PLATFORM=x64
%MSBUILD% /p:platform=%BUILD_PLATFORM% %MSBUILD_FLAGS%

set BUILD_PLATFORM=win32
%MSBUILD% /p:platform=%BUILD_PLATFORM% %MSBUILD_FLAGS%