#include "TestFwkHlp.h"
#include "TestFwk.h"

IMPL_DEFAULT_RUN_TEST(Export_CreoView)
IMPL_DEFAULT_VERIFY_TEST(Export_CreoView)

IMPL_DEFAULT_RUN_TEST(ExportPart_2D)
IMPL_DEFAULT_VERIFY_TEST(ExportPart_2D)

IMPL_DEFAULT_RUN_TEST(ExportPart_Image)
IMPL_DEFAULT_VERIFY_TEST(ExportPart_Image)

IMPL_DEFAULT_RUN_TEST(ExportPart_3D)
IMPL_DEFAULT_VERIFY_TEST(ExportPart_3D)

IMPL_DEFAULT_RUN_TEST(ExportDrw)
IMPL_DEFAULT_VERIFY_TEST(ExportDrw)

IMPL_DEFAULT_RUN_TEST(ExportAsm_2D)
IMPL_DEFAULT_VERIFY_TEST(ExportAsm_2D)

IMPL_DEFAULT_RUN_TEST(ExportAsm_3D)
IMPL_DEFAULT_VERIFY_TEST(ExportAsm_3D)