/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nextlabs_racrmx_RACRMXInstance */

#ifndef _Included_com_nextlabs_racrmx_RACRMXInstance
#define _Included_com_nextlabs_racrmx_RACRMXInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nextlabs_racrmx_RACRMXInstance
 * Method:    loadDRmUser
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nextlabs_racrmx_RACRMXInstance_loadDRmUser
  (JNIEnv *, jobject);

/*
 * Class:     com_nextlabs_racrmx_RACRMXInstance
 * Method:    loadDRmInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nextlabs_racrmx_RACRMXInstance_loadDRmInstance
  (JNIEnv *, jobject);

/*
 * Class:     com_nextlabs_racrmx_RACRMXInstance
 * Method:    isFileProtected
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nextlabs_racrmx_RACRMXInstance_isFileProtected
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nextlabs_racrmx_RACRMXInstance
 * Method:    setViewOverlay
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nextlabs_racrmx_RACRMXInstance_setViewOverlay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nextlabs_racrmx_RACRMXInstance
 * Method:    renderOverlay
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nextlabs_racrmx_RACRMXInstance_renderOverlay
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nextlabs_racrmx_RACRMXInstance
 * Method:    clearViewOverlay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nextlabs_racrmx_RACRMXInstance_clearViewOverlay
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
