#!/bin/bash
#
# DESCRIPTION
#	Invoke PCV build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR=<path>
#		export BUILD_NUMBER=<#>
#		source setEnv
#		./buildPcv
#
# HUDSON BUILD:
#	cd $WORKSPACE
#	export NLEXTERNALDIR=c:/hudson/jobs/external_latest/workspace
#	export NLPROFSERVDIR=c:/depot/ProfessionServices/buildCommon
#	source setEnv
#	./buildPcv
#
# Compile
#

LOG_FILE=buildPcv.log

source ../version_control

(
set -x
# Extract Workspace and Hudson info (only if running on Hudson)
if [ "X${JENKINS_HOME}" != "X" -a -f ${JENKINS_HOME}/jobs/${JOB_NAME}/config.xml ]; then
	${WORKSPACE}/scripts/getGitWorkspaceInfo.pl ${JENKINS_HOME}/jobs/${JOB_NAME}/config.xml
fi

# Prepare environment
./configure || exit $?
source build.config

OSVERSION=`uname`

# Prepare dependencies
$ANT -f Build/build_xlib.xml || exit $?

# Compile code and build installers
make -f Build/Makefile.compile || exit $?

# Publish installers and artifacts
$ANT -f Build/build_publish.xml || exit $?
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}
